#!/bin/bash

# run local (non-RMI) version of Closed Loop Test Harness

# Script executes org.mbari.siam.foce.utils.CLOTH.main()
$JAVA -cp $SIAM_CLASSPATH \
-Djava.security.policy=$SIAM_HOME/properties/policy \
-Dsiam_home=$SIAM_HOME \
-Dsiam.log4j=$SIAM_HOME/properties/siam.log4j \
-Dlog4j.threshold=$LOG4J_THRESHOLD \
-Dexec_name=`basename "$0"` \
org.mbari.siam.foce.utils.CLOTH $*
