#!/bin/bash

# run remote CO2 Subsystem Monitor utility

# Script executes org.mbari.siam.foce.utils.CO2MonitorUtil
$JAVA -cp $SIAM_CLASSPATH \
-Djava.security.policy=$SIAM_HOME/properties/policy \
-Dlog4j.threshold=$LOG4J_THRESHOLD \
-Dexec_name=`basename "$0"` \
org.mbari.siam.foce.utils.CO2MonitorUtil $@
