#!/bin/bash

# run local (non-RMI) version of motor utility

# Script executes org.mbari.siam.foce.utils.ElmoLocal.main()
$JAVA -cp $SIAM_CLASSPATH \
-Djava.security.policy=$SIAM_HOME/properties/policy \
-Dlog4j.threshold=$LOG4J_THRESHOLD \
-Dexec_name=`basename "$0"` \
org.mbari.siam.foce.utils.ElmoLocal $*
