#!/bin/bash
#

DEV_IDS="1642 1649 1728 1729" # 1642,1649:SBE52MP 1728,1729:Elmo
STREAM_NAME="sensors"
# use -k to keep going on error
KEEP_GOING="$1"
MONITOR=$SIAM_HOME/utils/foce/monitor

# ---- should not need to configure anything below this line ----
$MONITOR $KEEP_GOING $STREAM_NAME $DEV_IDS


