#!/bin/sh
#
# start/stop sa1100gpio driver

case "$1" in
    start)
        echo -n "Configuring sa1100_gpio gpio port: "
	insmod -o sa1100_gpio /root/sa1100gpio.o
	echo "done."
	;;
    stop)
        echo -n "Deconfiguring sa1100_gpio gpio port: "
        rmmod sa1100_gpio
	echo "done."
	;;
    reload)
	;;
    force-reload)
	$0 restart
	;;
    restart)
	;;
    *)
	echo "Usage: /etc/init.d/loadgpio {start|stop|reload|restart}"
	exit 1
	;;
esac

exit 0

