#!/bin/csh
#########################################################################
#               SIAM Acceptance Test Procedure
#
# Name:
#
# Description:
#
# Requirements addressed:
# (Requirements document at http://blahblahblah) 
#
# Procedure:
#
# $Id: atpTemplate,v 1.1 2008/11/04 21:57:02 bobh Exp $
# $Name: HEAD $
# $Log: atpTemplate,v $
# Revision 1.1  2008/11/04 21:57:02  bobh
# Initial checkin.
#
# Revision 1.1.1.1  2008/11/04 19:01:52  bobh
# Initial release of SIAM2, the release that was modularized to isolate hardware dependencies, and refactored to make most packages point to org.mbari.siam.
#
# Revision 1.1  2003/09/29 23:18:00  oreilly
# no message
#
# Revision 1.1  2003/09/26 16:39:25  oreilly
# Template for ATP scripts
#
#########################################################################
