/*
Copyright 2013 MBARI, all rights reserved. 
For license and copyright details, see COPYRIGHT.TXT in the SIAM project
home directory.
*/

package org.mbari.siam.distributed;

/** 
    NodePacketTypes defines SensorDataPacket "record types" generated by 
    Node. */
public class NodePacketTypes {
    public static final long PORT_SUMMARY = 1;
    public static final long POWER_PORT = 2;
    public static final long NULL_POWER_PORT = 3;
    public static final long GPS = 4;
    public static final long ENVIRONMENTAL = 5;
    public static final long FILESYSTEM = 6;
    public static final long JVM = 7;
    public static final long RFIO = 8;
    public static final long OPTICAL = 9;
    public static final long GLOBALSTAR = 10;
    public static final long WATCHDOG = 11;
    public static final long SLEEPLOG = 12;
}


