#!/bin/bash
# Get Vector averageVelocity data
#
$JAVA -cp $SIAM_CLASSPATH -Djava.security.policy=$SIAM_HOME/properties/policy \
-Dlog4j.threshold=$LOG4J_THRESHOLD org.mbari.siam.tests.rbnb.RBNBVectorTest $*
