#!/bin/bash

#-Dlog4j.logger.org.mbari.siam.foce.devices.controlLoop.OSDTConnectorWorker=INFO 
#-Dlog4j.logger.org.mbari.siam.foce.devices.controlLoop.WorkerThread=INFO 
#-Dlog4j.logger.org.mbari.siam.utils.TCPClient=INFO 

$JAVA -cp $SIAM_CLASSPATH \
org.mbari.siam.tests.devices.BB232SPDA.TestBB232SPDA $*