#!/bin/bash

# bcasts - broadcast test server
# Listens for UDP broadcast packets on a specified host address and port.
# When a packet is received, it echoes it backe to a waiting bcast client
# (see bcastc)
# Use 'bcasts --help' for options

$JAVA -cp $SIAM_CLASSPATH org.mbari.siam.tests.bcast.bcastsvr $*
