#!/bin/bash

# Autoscript
#
# Purpose: report tmpfs use

#########################
# Script configuration
#########################
export LOG4J_THRESHOLD=INFO

# node host definitions
SURFACE=surface
SECONDARY=node21
BIN=node2

# define node and port
NODE=$SURFACE

#########################
# Main script entry point
#########################

# keep node awake
cpuAwake 600 $NODE

# check filesystem
df
du -ah /mnt/ramfs

# AUTOSCRIPT EOF
