#!/bin/bash

# Autoscript
#
# Purpose: MUCE wifi off

#########################
# Script configuration
#########################
export LOG4J_THRESHOLD=INFO

# node host definitions
SURFACE=surface
SECONDARY=node21
BIN=node2

# define node and port
NODE=$SECONDARY
PORT=/dev/ttySX11

#########################
# Main script entry point
#########################

# keep awake 
cpuAwake 600 $NODE

# send command...
powerDownPort $NODE $PORT

# verify status
portStatus $NODE $PORT
listPorts $NODE -stats

# AUTOSCRIPT EOF
