#!/bin/bash

# Autoscript
#
# Purpose: MUCE McLane Profiler Service off

#########################
# Script configuration
#########################
export LOG4J_THRESHOLD=INFO

# node host definitions
SURFACE=surface
SECONDARY=node21
BIN=node2

# define node and port
NODE=$BIN
PORT=/dev/ttySX5

#########################
# Main script entry point
#########################

# keep awake 
cpuAwake 600 $NODE

# send command...
shutdownPort $NODE $PORT

# verify status
portStatus $NODE $PORT
listPorts $NODE -stats

# AUTOSCRIPT EOF