#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

# Annotate service running on specified port
if [ ! -n "$3" ]
then
  echo "usage: `basename $0` nodeURL portName annotation"
  exit 1
fi  

notes=$3

$JAVA -cp $SIAM_CLASSPATH \
-Djava.security.policy=$SIAM_HOME/properties/policy \
org.mbari.siam.operations.utils.AnnotateService $1 $2 "-s" "$notes"


