#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

# bcastc - broadcast test client
# Sends a UDP broadcast packet to a waiting bcast server (see bcasts)
# and waits for it to return the packet.
# Use 'bcastc --help' for options

$JAVA -cp $SIAM_CLASSPATH org.mbari.siam.tests.bcast.bcastcli $*
