#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

# Persist properties of service on specified port
if [ ! -n "$2" ]
then
  echo "usage: `basename $0` nodeURL portName"
  exit 1
fi  
echo number of args: $#

# Script executes moos.deployed.NodeTest.main()
$JAVA -cp $SIAM_CLASSPATH \
-Djava.security.policy=$SIAM_HOME/properties/policy \
-Dlog4j.threshold=$LOG4J_THRESHOLD \
org.mbari.siam.operations.utils.CacheInstrumentProperties $*

