#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

if [ ! -n "$1" ]
then
  echo "usage: `basename $0` nodeURL"
  exit 1
fi  


nodeURL=$1


# Script executes moos.deployed.NodeTest.main()
$JAVA -cp $SIAM_CLASSPATH -Djava.security.policy=$SIAM_HOME/properties/policy \
org.mbari.siam.operations.utils.CallbackTest $nodeURL

