#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

# Disable sleep management on specified node

if [ ! -n "$1" ]
then
  echo "usage: `basename $0` nodeHost"
  exit 1
fi

setNodeProperty $1 "SleepManager.enabled=false"

