#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

# Extract Globalstar status message from syslog

grep RSSI /mnt/hda/logs/syslog.bak /var/log/syslog > /tmp/gsStats
tail -10 /tmp/gsStats



