#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

# Execute JUnit test runner on specified test class
$JAVA -cp ${SIAM_CLASSPATH}:${SIAM_HOME}/jars/junit.jar \
-Djava.security.policy=$SIAM_HOME/properties/policy \
-Djava.rmi.server.codebase=$SIAM_CODEBASE \
-Dsiam_home=$SIAM_HOME \
-Dsiam_port_cfg="/properties/siamPort.test" \
junit.swingui.TestRunner $*

