#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

#
if [ ! -n "$1" ]
then
  echo "usage: `basename $0` nodeURL portName"
  exit 1
fi  


#note this script needs hyperterm that supports WinSock sessions and hypertrm.exe
#needs to be locates in the SIAM_BIN directory

#suspend the driver
$SIAM_HOME/utils/suspendPort $*

#start serial console
$SIAM_BIN/hypertrm /t `$JAVA -cp $SIAM_CLASSPATH \
                      -Djava.security.policy=$SIAM_HOME/properties/policy \
                      org.mbari.siam.operations.utils.GetRemoteSerialPortParams $1 $2`
#resume the driver
$SIAM_HOME/utils/resumePort $*


