#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

$JAVA -cp $SIAM_CLASSPATH \
-Dsiam_home=$SIAM_HOME \
-Dlog4j.threshold=$LOG4J_THRESHOLD \
org.mbari.siam.operations.utils.FileJoinerUtil $*
