#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

# Kill j9 processes
pid=`ps -eaf | grep j9 | awk '{print $2; exit}'`
kill $pid

