#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

#

while [ 1 ]; do
    listPorts loc -stats
    sleep 10
done

