# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.


et2ut: et2ut.cc
	g++ -o et2ut et2ut.cc


ut2et: ut2et.cc
	g++ -o ut2et ut2et.cc



all: et2ut ut2et 
