#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

# Display load average information
while [ 1 ]
do
date
cat /proc/loadavg
echo
sleep 10
done
end
