#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

# Run netstat periodically
while [ 1 ]
do
  date
  netstat --tcp
  echo
  sleep 30
done
