#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

if [ ! -n "$3" ]
then
  echo "usage: `basename $0` nodeURL portName nTurns"
  exit 1
fi  
echo number of args: $#

# Script executes moos.deployed.NodeTest.main()
$JAVA -cp $SIAM_CLASSPATH \
-Djava.security.policy=$SIAM_HOME/properties/policy \
-Dlog4j.threshold=$LOG4J_THRESHOLD \
org.mbari.siam.operations.utils.ResetTurnsCounter $*

# Now get a sample to confirm reset
samplePort $1 $2

