#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

# Script to run the 'node' application 
#
export JAVA=j9
export JAVA_HOME=/j9
export PATH=.:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:$JAVA_HOME/bin:/root:/mnt/hda/siam/utils
export SIAM_HOME=/mnt/hda/siam
export SIAM_CLASSPATH=$JAVA_HOME/lib/jclMax/classes.zip:$JAVA_HOME/lib/prsnlmot.jar:$JAVA_HOME/lib/RXTXcomm.jar:$SIAM_HOME/classes:/mnt/hda/codebase:$SIAM_HOME/jars/gnu_getopt.jar:$SIAM_HOME/jars/javax.jar
#export SIAM_CODEBASE=http://sidearm12/codebase
export LD_LIBRARY_PATH=/usr/X11R6/lib:$JAVA_HOME/bin

cd /mnt/hda/siam
./utils/rfpower on
./utils/node shore >& ./logs/node.`/bin/date +%Y%m%d%H%M%S` &

