#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

if [ ! -n "$1" ]
then
	echo "usage: `basename $0` nodeURL"
	exit 1
fi

nodeURL=$1

# Keep target node awake
cpuAwake $nodeURL

# Tell node to safe safeable instruments
$JAVA -cp $SIAM_CLASSPATH -Djava.security.policy=$SIAM_HOME/properties/policy \
-Dlog4j.threshold=$LOG4J_THRESHOLD org.mbari.siam.operations.utils.SafeMode $nodeURL
