#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

while [ 1 ]
do 
date
getLastSample localhost 0 | grep ADC4
echo "----------"
sleep 600 
done
