#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

if [ ! -n "$2" ]
then
  echo "usage: `basename $0` nodeURL portName key=value <key=value><...>"
  exit 1
fi  

# Set specified property of specified instrument service
$JAVA -cp $SIAM_CLASSPATH \
-Djava.security.policy=$SIAM_HOME/properties/policy \
-Dlog4j.threshold=$LOG4J_THRESHOLD \
org.mbari.siam.operations.utils.SetInstrumentProperty ${1+"$@"}
#org.mbari.siam.operations.utils.SetInstrumentProperty $*

echo ""
echo "NOTE: property change will take effect when restartPort is executed"

