#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

# Call ifswitch-to-static script to place node on 134.89.36.X network.
/usr/bin/ifswitch-to-static

# Remove any problematic name resolution statements added by DHCP.
echo "" > /etc/resolv.conf
