#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

# Run a few tests on SIAM device service, as specified by URL
$JAVA $JAVA_OPTIONS -Dlog4j.threshold=$LOG4J_THRESHOLD \
-Dsiam_home=$SIAM_HOME -cp $SIAM_CLASSPATH -Djava.security.policy=$SIAM_HOME/properties/policy org.mbari.siam.tests.moos.devices.DeviceTest $*

