/*
Copyright 2013 MBARI, all rights reserved. 
For license and copyright details, see COPYRIGHT.TXT in the SIAM project
home directory.
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class moos_utils_SystemCall */

#ifndef _Included_moos_utils_SystemCall
#define _Included_moos_utils_SystemCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     moos_utils_SystemCall
 * Method:    call
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_moos_utils_SystemCall_call
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
