#!/usr/bin/bash

# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

export LOG4J_THRESHOLD=FATAL
rm packetStats-all.out

loc="."

if [ "$#" -ge 1 ]
then
    loc="$1"
fi

for dir in `ls --hide=[^0-9]* $loc` 
do
echo $dir
for id in `ls $loc/$dir/*dat|sed -e "s/.*\([0-9]*\/\)\([0-9][0-9][0-9][0-9]\).*/\2/"`
do
  echo "logView -statsOnly -noheader -notype $id $loc/$dir"
  logView -statsOnly -noheader -notype $id $loc/$dir >> packetStats-all.out
done
done