#!/bin/csh
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.

# Plot duration of ppp connections based on contents of /var/log/messages

if ($#argv != 2) then
  echo "Usage: $0 ppp-endpoint-IP max-days"
  exit 1
endif


# Create awk script to extract duration as function of time
set awkscript=/tmp/tmp$$.awk
cat > $awkscript << 'EOF'

BEGIN {

  dateCmd = "date +%s";
  dateCmd | getline now;

  close(dateCmd);
  targetIP = ARGV[1];
  ARGV[1] = "";

  maxAgeDays = ARGV[2];
  ARGV[2] = "";

  connectMsg = "IP-UP.*" targetIP;
  disconnectMsg = "IP-DOWN.*" targetIP;
}

{
  # Age of record in days
  age = (now - $2)/3600./24.;
  if (age > maxAgeDays) {
    next;
  }
}

$0 ~ connectMsg {
  start = $2;
}

$0 ~ disconnectMsg {

  if (start > 0) {   # Need at least 1 'IP-UP' to compute duration
    duration = $2 - start;
    printf "%s %s %s %s %d\n", $3, $4, $5, $6, duration;
  }
}


'EOF'

# Execute awk script to extract duration as function of time
set datafile=/tmp/ppp-duration
awk -f $awkscript $argv[1] $argv[2] /var/log/ppp.log > $datafile

# Create gnuplot script to plot duration as function of time
set plotscript=/tmp/gnuplot.$$
cat > $plotscript << EOF2

set xdata time
set timefmt "%b %d %Y %H:%M:%S"
set yrange [0:2400]
set terminal png
set output "ppp-duration.png"
set title "PPP connection duration"
# Need place-holder for xlabel for proper spacing...
set xlabel "Local time"
set ylabel "Connection duration (sec)"
plot "/tmp/ppp-duration" using 1:5 with linespoints

EOF2

cat $plotscript | gnuplot 



