#!/bin/bash
# Copyright 2013 MBARI, all rights reserved. 
# For license and copyright details, see COPYRIGHT.TXT in the SIAM project
# home directory.



$JAVA -cp $SIAM_CLASSPATH org.mbari.siam.operations.portal.StatsAnalyzer $*